cc_library(
  name="MemoryResources",
  srcs=glob(["src/*.cxx", "include/MemoryResources/*.h"]),
  includes=["include"],
  visibility = ["//visibility:public"],
  deps = [
      "@boost//:container",
      "@fairmq//:FairMQ"
      ]
)
