cc_library(
  name="Headers",
  srcs=glob(["src/*.cxx", "include/Headers/*.h"]),
  includes=["include"],
  visibility = ["//visibility:public"],
  deps = [
      "//DataFormats/MemoryResources:MemoryResources"
      ]
)
